export default {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',
    FETCH_GITHUB_INFO: 'FETCH_GITHUB_INFO',
    FETCH_GITHUB_COMMITS: 'FETCH_GITHUB_COMMITS',
    FETCH_GITHUB_REPOS: 'FETCH_GITHUB_REPOS',
    FETCH_GITHUB_ACTIVITY: 'FETCH_GITHUB_ACTIVITY'
}