export default {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    THEME_WAS_CHANGED:'THEME_WAS_CHANGED',
    LOADING_CHANGE: 'LOADING_CHANGE',
    FETCH_USER: 'FETCH_USER',
    INSULT_FETCHED: 'INSULT_FETCHED',
    UPDATE_USER: 'UPDATE_USER',

}