export default {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    THEME_WAS_CHANGED:'THEME_WAS_CHANGED',
    LOADING_CHANGE: 'LOADING_CHANGE',
    FETCH_USER: 'FETCH_USER',
    INSULT_FETCHED: 'INSULT_FETCHED',
    UPDATE_USER: 'UPDATE_USER',
    USERFEED_FETCHED: 'USERFEED_FETCHED',
    FETCH_NEW_COMMITS: 'FETCH_NEW_COMMITS',
    POSTED_TO_USERFEED: 'POSTED_TO_USERFEED',
    DISCOVERFEED_FETCHED: 'DISCOVERFEED_FETCHED',
    POST_SELECTED: 'POST_SELECTED',
    USER_SELECTED: 'USER_SELECTED',
    FEED_POSTED: 'FEED_POSTED'
}